### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by icaroerasmo** [TomasHubelbauer/node-apng#2]
Hi!

It's been some time since I ran this lib with the code I built myself without any issue. Today I was making some refactors and then this error appeared when I tried to run a pod in docker with the same code:

```
/usr/src/app/node_modules/node-apng/index.js:1
import crc from 'crc';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/br/com/guide-automator/libs/Recorder.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
```

**Comment by TomasHubelbauer** [comment]
Hello, what version of Node are you running? And do you have `{ type: 'module' }` in your `package.json`? Node 15+ is ideal (as it has ESM support without a CLI flag).
